-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Сен 26 2022 г., 01:15
-- Версия сервера: 10.4.24-MariaDB
-- Версия PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `news_data`
--

-- --------------------------------------------------------

--
-- Структура таблицы `news`
--

CREATE TABLE `news` (
  `id` int(11) DEFAULT NULL,
  `idate` int(11) DEFAULT NULL,
  `title` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `announce` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Дамп данных таблицы `news`
--

INSERT INTO `news` (`id`, `idate`, `title`, `announce`, `content`) VALUES
(1, 1318222200, 'Lorem ipsum dolor sit amet. Et voluptas ullam et aspernatur iusto', 'Lorem ipsum dolor sit amet. Et voluptas ullam et aspernatur iusto et quia quibusdam ex esse quia eum nihil omnis  neque molestias. Ea pariatur omnis ea omnis labore et recusandae reiciendis qui laboriosam aperiam qui enim voluptate ut atque minus. Id internos voluptatem qui quia incidunt non vitae omnis ea illum quaerat sed sunt quaerat ea deserunt laboriosam et quasi internos. In ullam deserunt aut quas officia cum alias deleniti ut aperiam \r\n', 'Lorem ipsum dolor sit amet. Et voluptas ullam et aspernatur iusto et quia quibusdam ex esse quia eum nihil omnis  neque molestias. Ea pariatur omnis ea omnis labore et recusandae reiciendis qui laboriosam aperiam qui enim voluptate ut atque minus. Id internos voluptatem qui quia incidunt non vitae omnis ea illum quaerat sed sunt quaerat ea deserunt laboriosam et quasi internos. In ullam deserunt aut quas officia cum alias deleniti ut aperiam consequuntur ut dolores deserunt in repellendus aliquam. Eum dignissimos quas aut molestiae aliquam vel magnam possimus est error ratione. Quo sunt mollitia et maxime delectus non aspernatur doloremque non voluptatem eius ex nihil sequi eos corporis enim aut velit obcaecati! Sed incidunt iste hic dolores asperiores qui corrupti odit et similique iste non doloremque fugit quo veniam voluptatum et cupiditate corporis? Ut perspiciatis modi ut aperiam voluptatem et magnam labore in quia voluptates. Rem error reiciendis qui quam eligendi ex maiores eaque et dolorum optio ex consequatur omnis ut autem eius. \r\n'),
(2, 1317731200, 'Lorem ipsum dolor sit amet. Ut internos labore', 'Lorem ipsum dolor sit amet. Ut internos labore ut expedita voluptatem sed omnis distinctio qui quibusdam doloribus est officia odio. At quisquam beatae qui Quis dolore qui aliquid quam in quia reiciendis aut veritatis placeat sed maiores illo non dolores saepe. Aut odit harum  amet officiis et doloremque quas et nisi ratione ad porro voluptates ea ', 'Lorem ipsum dolor sit amet. Ut internos labore ut expedita voluptatem sed omnis distinctio qui quibusdam doloribus est officia odio. At quisquam beatae qui Quis dolore qui aliquid quam in quia reiciendis aut veritatis placeat sed maiores illo non dolores saepe. Aut odit harum  amet officiis et doloremque quas et nisi ratione ad porro voluptates ea sunt animi. Sed aperiam dolor sed modi consectetur ab perferendis quisquam id rerum dolores eum officia placeat! Qui nemo repellendus At ducimus corporis hic quidem sequi. Et dolorem rerum est nisi rerum sed cupiditate totam et fuga aspernatur eum culpa quos sed dolore quibusdam. Ea facere fugit ut tempora Quis quo Quis deserunt qui rerum eaque. Est provident dolores eos debitis ullam aut sunt officia hic debitis tenetur. Eum sapiente distinctio sed enim eaque sit cupiditate aspernatur aut asperiores reiciendis quo officiis accusamus. Ea iusto consequatur qui beatae quas et magni minima aut fugiat animi. \r\n'),
(3, 1318721200, 'Lorem ipsum dolor sit amet. Id error', 'Lorem ipsum dolor sit amet. Id error harum aut corrupti ipsum aut voluptas reprehenderit nam consequatur quis et deserunt libero et consequatur rerum. Aut soluta officiis et autem reprehenderit est dolores similique. Eum beatae expedita ea quia quod hic dolorem inventore et quod nobis eos minima obcaecati 33 enim dolorem!', 'Lorem ipsum dolor sit amet. Id error harum aut corrupti ipsum aut voluptas reprehenderit nam consequatur quis et deserunt libero et consequatur rerum. Aut soluta officiis et autem reprehenderit est dolores similique. Eum beatae expedita ea quia quod hic dolorem inventore et quod nobis eos minima obcaecati 33 enim dolorem! Ut aspernatur earum eos illo odio aut pariatur neque et consequuntur beatae et asperiores cupiditate non accusantium nostrum cum debitis dolorum. Sit rerum iure et fugiat mollitia qui illum delectus ut dolorum distinctio sed reprehenderit fuga sed earum veniam aut iusto dolorem. Ab vero molestiae est pariatur voluptatem est voluptatem rerum et dolorem doloribus. 33 nemo soluta et maiores provident eum maiores ratione ut internos adipisci. Qui galisum accusamus ut eveniet consequatur id ratione omnis. In vitae quos ad internos debitis ut doloribus dolor. Non magnam iusto aut odio voluptas est enim possimus et quisquam earum sed minus deleniti qui pariatur excepturi ab molestias placeat.'),
(4, 1318531100, 'Lorem ipsum dolor sit amet. Id error harum \r\n', 'Lorem ipsum dolor sit amet. Id error harum aut corrupti ipsum aut voluptas reprehenderit nam consequatur quis et deserunt libero et consequatur rerum. Aut soluta officiis et autem reprehenderit est dolores similique. Eum beatae expedita ea quia quod hic dolorem inventore et quod nobis eos minimacupiditate non accusantium nostrum cum debitis dolorum. Sit rerum iure et fugiat mollitia qui illum delectus ut dolorum distinctio sed reprehenderit fuga sed earum veniam aut iusto dolorem. Ab vero molestiae est pariatur  \r\n', 'Lorem ipsum dolor sit amet. Id error harum aut corrupti ipsum aut voluptas reprehenderit nam consequatur quis et deserunt libero et consequatur rerum. Aut soluta officiis et autem reprehenderit est dolores similique. Eum beatae expedita ea quia quod hic dolorem inventore et quod nobis eos minima obcaecati 33 enim dolorem! Ut aspernatur earum eos illo odio aut pariatur neque et consequuntur beatae et asperiores cupiditate non accusantium nostrum cum debitis dolorum. Sit rerum iure et fugiat mollitia qui illum delectus ut dolorum distinctio sed reprehenderit fuga sed earum veniam aut iusto dolorem. Ab vero molestiae est pariatur voluptatem est voluptatem rerum et dolorem doloribus. 33 nemo soluta et maiores provident eum maiores ratione ut internos adipisci. Qui galisum accusamus ut eveniet consequatur id ratione omnis. In vitae quos ad internos debitis ut doloribus dolor. Non magnam iusto aut odio voluptas est enim possimus et quisquam earum sed minus deleniti qui pariatur excepturi ab molestias placeat. \r\n'),
(5, 1318661200, 'Lorem ipsum dolor sit amet. Vel iusto omnis', 'Lorem ipsum dolor sit amet. Vel iusto omnis et illum culpa 33 nobis veritatis ab omnis ratione nam quisquam fuga a eius numquam est cumque internos. Qui sapiente voluptatem eum laborum magni ea mollitia recusandae quo molestiae distinctio 33 maxime ducimus. Ea fugit dolor sit maiores internos et ipsum nemo. Et corporis praesentium est ', 'Lorem ipsum dolor sit amet. Vel iusto omnis et illum culpa 33 nobis veritatis ab omnis ratione nam quisquam fuga a eius numquam est cumque internos. Qui sapiente voluptatem eum laborum magni ea mollitia recusandae quo molestiae distinctio 33 maxime ducimus. Ea fugit dolor sit maiores internos et ipsum nemo. Et corporis praesentium est voluptas magnam ut facilis recusandae est facilis nemo vel veniam quidem ut repellat maxime aut animi nobis. Quo fugiat voluptatem non quasi rerum et eveniet natus aut maiores cumque nam officia impedit. Qui quia molestiae et quidem iste vel debitis nisi est provident sunt a sequi nostrum in voluptatum amet.'),
(6, 1318721200, 'Lorem ipsum dolor sit amet. Qui', 'Lorem ipsum dolor sit amet. Qui deserunt doloremque et ipsa est quaerat adipisci et odio voluptatem et numquam unde. Sed iure Quis id atque quaerat id quaerat galisum. Est quis quasi et praesentium galisum et accusamus voluptatem et voluptas consectetur et rerum mollitia non nihil provident. Et iure illum eum adipisci quasi ad illo dolorum et doloribus facr eligendi aut similique facilis in nihil vero. Id animi dicta qui voluptatibus explicabo ut quaerat saepe aut suscipit maxime.', 'Lorem ipsum dolor sit amet. Qui deserunt doloremque et ipsa est quaerat adipisci et odio voluptatem et numquam unde. Sed iure Quis id atque quaerat id quaerat galisum. Est quis quasi et praesentium galisum et accusamus voluptatem et voluptas consectetur et rerum mollitia non nihil provident. Et iure illum eum adipisci quasi ad illo dolorum et doloribus facere. Est rerum itaque non veniam sint est provident ut nihil quia et molestiae omnis ex internos amet et nobis pariatur. Hic dolorum sint aut Quis quis eum suscipit tenetur aut aperiam aliquam 33 aspernatur nesciunt ab numquam galisum quo rerum omnis? Aut vitae nemo in galisum veniam aut velit nobis sed voluptas quia. Sit odio galisum est aspernatur eligendi aut similique facilis in nihil vero. Id animi dicta qui voluptatibus explicabo ut quaerat saepe aut suscipit maxime.'),
(7, 1318721100, 'Lorem ipsum dolor sit amet. Qui nulla voluptas et totam accus', 'Lorem ipsum dolor sit amet. Qui nulla voluptas et totam accusamus rem reprehenderit autem. Sed temporibus adipisci et dolores quia qui quia eligendi! Non quaerat vitae ut aperiam ratione 33 quis illum qui quod rerum. Nam exercitationem incidunt id adipisci vero est necessitatibus quae vel eius amet non minus sequi sit impedit fugit ', 'Lorem ipsum dolor sit amet. Qui nulla voluptas et totam accusamus rem reprehenderit autem. Sed temporibus adipisci et dolores quia qui quia eligendi! Non quaerat vitae ut aperiam ratione 33 quis illum qui quod rerum. Nam exercitationem incidunt id adipisci vero est necessitatibus quae vel eius amet non minus sequi sit impedit fugit ea ullam voluptates! Quo porro similique sit architecto officiis ab velit cumque est omnis voluptas qui consequatur neque? Ab maxime dolores nam assumenda dolor ab perferendis voluptatum. Aut velit minus non temporibus facilis aut repudiandae Quis eos dolorem reiciendis rem accusantium omnis eum ducimus fugit '),
(8, 1318751312, 'Lorem ipsum dolor sit amet. Qui odio omnis', 'Lorem ipsum dolor sit amet. Qui odio omnis eum illum sint et omnis cupiditate id aperiam numquam sit fuga excepturi. Qui autem incidunt aut quis sint et voluptas ipsa aut corporis ratione ab sint sunt et eligendi dolores. Qui voluptatibus odit quo dicta tempore ut asperiores reprehenderit nam quae optio id ullam fugit ut illum tempore. Eos ', 'Lorem ipsum dolor sit amet. Qui odio omnis eum illum sint et omnis cupiditate id aperiam numquam sit fuga excepturi. Qui autem incidunt aut quis sint et voluptas ipsa aut corporis ratione ab sint sunt et eligendi dolores. Qui voluptatibus odit quo dicta tempore ut asperiores reprehenderit nam quae optio id ullam fugit ut illum tempore. Eos voluptatem ipsam aut quia unde sed asperiores alias qui dolorem tempore. Et veniam commodi ut deserunt molestias et cupiditate excepturi et reprehenderit sint vel ipsam inventore. In eius fuga cum consequatur vitae vel soluta dolore ut quis nostrum ad quis quia At alias minus. Ut quaerat internos eum exercitationem ducimus non eligendi ducimus. Est debitis optio aut voluptate veritatis ut aliquid tenetur ut magnam facilis ut velit temporibus aut porro consequatur non nihil excepturi. Est omnis dolores et dolor facere rem accusantium autem in facilis esse. In earum esse aut repellendus voluptates ex aspernatur dolorem et facilis corrupti? Qui tempora optio et dicta blanditiis vel tempora atque eum atque eaque. Ut laudantium exercitationem et quibusdam dolores in maxime minus.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
